name = "lgproducts2026"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"
assets = { directory = ".open-next/assets", binding = "ASSETS" }

[[d1_databases]]
binding = "lg_product_db"
database_name = "lg-product-db"
database_id = "7dbc7a79-8c22-4b17-9429-9210cea01332"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "lg_product_images"
bucket_name = "lg-product-images"
